useful_strings = [
    "PhotonEnergy",
    "PolarMode",
    "SampleTemp",
    "SampleXs",
    "SampleYs",
    "SampleZ",
    "SampleTheta",
    "SamplePhi",
    "SampleTilt",
    "AcquireTime",
    "ExposureSplit",
    "ExitSlit",
    "BeamCurrent",
    ]